services:
  db:
    image: postgres:16
    container_name: rental_db
    environment:
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_pass
      POSTGRES_DB: rental_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    networks:
      - rental-net

  auth_service:
    build: ./auth-service
    container_name: auth_service
    depends_on:
      - db
    ports:
      - "8001:8001"
    networks:
      - rental-net  

  property_service:
    build: ./property-service
    container_name: property_service
    depends_on:
      - db
    ports:
      - "8002:8002"
    networks:
      - rental-net  

  leasing_service:
    build: ./leasing-service
    container_name: leasing_service
    depends_on:
      - db
    ports:
      - "8003:8003"
    networks:
      - rental-net  

  frontend_service:
    build: ./frontend-service
    container_name: frontend_service
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - property_service
      - leasing_service
    networks:
      - rental-net

volumes:
  pgdata:

networks:
  rental-net:
