version: "3.8"

services:
  db:
    image: postgres:16
    container_name: rental_db
    environment:
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_pass
      POSTGRES_DB: rental_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
    networks:
      - rental-net

  auth-service:
    build: ./auth-service
    container_name: auth_service
    depends_on:
      - db
    ports:
      - "8001:8001"
    networks:
      - rental-net  

  property-service:
    build: ./property-service
    container_name: property_service
    depends_on:
      - db
    ports:
      - "8002:8002"
    networks:
      - rental-net  

networks:
  rental-net:

volumes:
  pgdata:
